import json
from typing import Dict, Any, Optional
from urllib.parse import urlparse, parse_qs

def generate_postman(url: str, method: str, headers: Optional[Dict[str, str]] = None,
                     body: Optional[Any] = None, query_params: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    """Generate Postman Collection v2.1 JSON from API specification."""
    
    # Parse URL
    parsed_url = urlparse(url)
    
    # Build host array (split by dots)
    host = parsed_url.netloc.split('.') if parsed_url.netloc else []
    
    # Build path array (split by slashes, filter empty)
    path = [p for p in parsed_url.path.split('/') if p]
    
    # Build query array
    query_array = []
    if query_params:
        for key, value in query_params.items():
            query_array.append({
                "key": key,
                "value": value
            })
    
    # Build headers array
    header_array = []
    if headers:
        for key, value in headers.items():
            header_array.append({
                "key": key,
                "value": value
            })
    
    # Build request object
    request = {
        "method": method,
        "header": header_array,
        "url": {
            "raw": url,
            "protocol": parsed_url.scheme,
            "host": host,
            "path": path
        }
    }
    
    # Add query parameters to URL if present
    if query_array:
        request["url"]["query"] = query_array
    
    # Add body (only for non-GET requests)
    if body is not None and method != "GET":
        if isinstance(body, (dict, list)):
            request["body"] = {
                "mode": "raw",
                "raw": json.dumps(body, indent=2),
                "options": {
                    "raw": {
                        "language": "json"
                    }
                }
            }
        else:
            request["body"] = {
                "mode": "raw",
                "raw": str(body)
            }
    
    # Build collection
    collection = {
        "info": {
            "name": "Generated API Request",
            "description": "Generated by API Code Generator",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [
            {
                "name": f"{method} {url}",
                "request": request
            }
        ]
    }
    
    return collection
